### ISSUE TITLE
Multiple charts on the same page

### ISSUE THREAD

**Issue by ttj101** [ArielMejiaDev/larapex-charts#1]
Hi,

Thank you for the plugin it's really easy to work with.

I can't seem to be able to have more than one chart in page, if i have more than one chart it seems like every chart overwrites all the previous.

**Comment by ArielMejiaDev** [comment]
Hi thanks for using the library, I am working to fix the issue with Facade at this moment you can work with the base class that the package provide without any trouble, this is an example: 

```php

use ArielMejiaDev\LarapexCharts\LarapexChart;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/charts', function(){

    $pieChart = (new LarapexChart)->setTitle('Users')->setXAxis(['Active', 'Guests'])->setDataset([
        100, 200
    ]);
    $areaChart = (new LarapexChart)->setType('area')
    ->setTitle('New Users Monthly')
    ->setSubtitle('From January to March')
    ->setXAxis([
        'Jan', 'Feb', 'Mar'
    ])
    ->setDataset([
        [
            'name'  =>  'New Users',
            'data'  =>  [250, 700, 1200]
        ]
    ]);
    return view('charts', compact('pieChart', 'areaChart'));

});

```

I can provide a patch release during this weekend or maybe even today, thanks for using the library, I will notify in this thread when the library will be updated.
