### ISSUE TITLE
Problem in laravel 11, Command make:chart is ERROR

### ISSUE THREAD

**Issue by jarwonozt** [ArielMejiaDev/larapex-charts#104]
I tried to install it successfully, but the command doesn't work when I run the command ```php artisan make:chart MonthlyUserChart``` , is there a solution?

Thank You

SS :
![image](https://github.com/ArielMejiaDev/larapex-charts/assets/67833034/af6fadb0-fb71-408a-b859-066feed4b123)

**Comment by NightcoreDragun** [comment]
Same issue here, i think that there are issue with the providers, trying to check if that the issue.

**Comment by stevegoddard** [comment]
This package really doesn't seem happy with Laravel 11. I had to remove the package to upgrade from L10 to L11. When I re-added the package it insisted on version 2.1! 

I think the issue is here:

    arielmejiadev/larapex-charts 8.1.0 requires illuminate/support ^9.0|^10.0

I think this needs bumping to ^11.0?

**Comment by synsa** [comment]
Same issue, came here to see if it was reported.

**Comment by shadowoff09** [comment]
Same issue here.

**Comment by marineusde** [comment]
I published a fork of the project some days ago and have done some codestyle, bugfixed ect. I fixed the make:chart-command and all the stubs now for you and tested it with a new laravel 11 project in Version 1.2.2:

https://github.com/marineusde/larapex-charts

**Comment by jarwonozt** [comment]
> I published a fork of the project some days ago and have done some codestyle, bugfixed ect. I fixed the make:chart-command and all the stubs now for you and tested it with a new laravel 11 project in Version 1.2.3:
> 
> https://github.com/marineusde/larapex-charts

OK bro, I'll try later.

**Comment by drakanor** [comment]
Works well with Laravel 11. Good job.

**Comment by ArielMejiaDev** [comment]
I am going to check this issue, thanks

**Comment by majweb** [comment]
still not work command make:chart :(

**Comment by jarwonozt** [comment]
> I am going to check this issue, thanks

okay, I'm waiting for the latest update, cheers up

**Comment by jarwonozt** [comment]
> I am going to check this issue, thanks

okay, I'm waiting for the latest update, cheers up

**Comment by jarwonozt** [comment]
> There is still a problem with the make:chart command. Can't find this command. :(

I hope it updates quickly

**Comment by marineusde** [comment]
Did you test my fork with the command?

**Comment by heymicoo** [comment]
Has this been resolved?

**Comment by heymicoo** [comment]
@marineusde Can you submit a PR to the main repo instead of creating a fork please?

**Comment by marineusde** [comment]
I tried pull requrests to this repo, but the maintainer closed it cause there are "to many changes". My company use the apex charts in some projects so I do a fork to solve the problems and add more features.

I have no problem working in active repos if the maintainer want it.

**Comment by coirpower** [comment]
Thanks, @marineusde! Laravel 11 is good for me now 👍 
Hope the fix will be soon implemented into this repo as well.
