### ISSUE TITLE
Changes to work in Laravel 10-11 Inertia

### ISSUE THREAD

**Issue by Altffenser** [ArielMejiaDev/larapex-charts#105]
I had to make some adjustments to make it work correctly, since this package stopped working after Laravel version 10.

Understanding Inertia's Shared Data concept, it is no longer possible to access the `chart.x ` variable from the definition. And that is precisely the error presented in my case with Laravel 10, intertia and Vue 3. 

The solution:
In any of our components (Remember, the `<script>` tag must specify the `setup `property).

```js
import {usePage} from "@inertiajs/vue3";
```

```js
const props = {
    chart: usePage().props.chart
}
```

```vue
<apexchart :width="props.chart.width" :height="props.chart.height" :type="props.chart.type" :options="props.chart.options"
                           :series="props.chart.series"></apexchart>
```

That's it, this should work again.

**Comment by darkons** [comment]
What does this have to do with the Larapex charts package?
There is no problem, it all depends on your implementation.
I'm using the latest version with Laravel 10 + Inertia and I have no problems.

**Comment by ArielMejiaDev** [comment]
As @darkons said there are no issues to use the package with inertia, at this moment you can find even examples in the docs
