### ISSUE TITLE
How do I avoid converting whole numbers to decimals?

### ISSUE THREAD

**Issue by alexv96** [ArielMejiaDev/larapex-charts#11]
I'm working with years as an axis and he put the years with decimals, how could I remove it?

**Comment by ArielMejiaDev** [comment]
This is something that cannot be added, the package build a php representation object of a javascript object to build a chart, so in blade views or Vue components, (files that area supported at this time) so since what render is javascript it cannot work with long numbers without decimals.

**Comment by ArielMejiaDev** [comment]
So this cannot be added by javascript limitations
