### ISSUE TITLE
Mixed Chart

### ISSUE THREAD

**Issue by bhavikf** [ArielMejiaDev/larapex-charts#17]
Hello,

Thanks for such a great package.

I would like to use it in one of the app that i am working on but the real question I have is can we use the mixed type chart that is with BarChart and Line Chart on top of it whereas Y Axis on left side can denote the value for Line Chart whereas Y Axis on Right side denote the value for Bar Chart. 

Appreciate your quick response. 

Thanks,
Bhavik

**Comment by ArielMejiaDev** [comment]
Hi @bhavikf at this moment the docs have the charts that are available, on every release I add more charts, but at this moment the mixed charts are not available.

But, you can extend from LarapexChart class and add/override the methods needed to add your own implementation.

I even accept Pull Requests to add this type of chart, so feel free to make a PR if you want.
