### ISSUE TITLE
Is it possible to change the color of the text?

### ISSUE THREAD

**Issue by Retropartidas** [ArielMejiaDev/larapex-charts#18]
I am using charts on a black background, and I would like the text to be white, but it is not possible and can hardly be read

https://i.imgur.com/DdyExFI.png

https://i.imgur.com/xASF0Cy.png

**Comment by ArielMejiaDev** [comment]
Hi @Retropartidas, this is something  that is requested more than one time, so I would schedule it on TO DO list of the package for next version.

At this moment you can do this:

- if you are working with blade, publish the blade view file and make the changes that you need
- if you are working with VueJS components you can override this property directly on the component prop as a merge property, so it would render with the change.
