### ISSUE TITLE
setting custom tags

### ISSUE THREAD

**Issue by ecoplace** [ArielMejiaDev/larapex-charts#2]
Hi there,

Thank you for the package, its excellent to work with.
Have you considered adding the ability to set custom tags, such as setCustom('sparkline: {enabled: !0}');

**Comment by yusofy** [comment]
I second @ecoplace so far great package and very simple to work with! I was looking around for the custom tags to have the ability to call stuff from the original framework. I think that'd be an excellent addition to this great project!

**Comment by ArielMejiaDev** [comment]
Hi there! thanks for using the package, @yusofy and @ecoplace to add custom tags, I need a case of use to really understand how do you prefer to be implemented, please provide some code like a wishful thinking it would help to understand better what could be needed, the same for custom tags, please provide me a little example how do you expected to use it, thanks again for your comments :)

**Comment by tomcrofty** [comment]
Sorry to bring up a closed issue but the use-case for this would be to work with ApexCharts options that haven't got getters and setters available. For instance, if I wanted to make a sparkline chart, the only way at the moment would be to edit the script stub, ideally there would be a function of LarapexChart called `setCustom` allowed us to apply custom properties to the charts object.

The easiest way I can see of doing this would be to take in two parameters, an index parameter as an array and a value param. So we'd end up with something like:
`->setCustom(['chart', 'sparkline'], true);`
This would set the sparkline property of the chart to the value provided. You'd need some sort of recursive function to be able to find the specific array element. I'll see if I can push a PR for this or post some exampels here.
