### ISSUE TITLE
Add print method to charts ?

### ISSUE THREAD

**Issue by chatsikm** [ArielMejiaDev/larapex-charts#20]
Greetings, since i dont see in the documentation any method to print the chart , is it easy to implement or at least indicate me how to implement it? 

Thanks in advance

**Comment by ArielMejiaDev** [comment]
This is not really a package issue, but you can use Javascript to implement this behavior easily, here a post where I explain how to implement it: https://dev.to/arielmejiadev/print-a-div-tag-content-with-javascript-4a35

You can use server side to print a whole view, it would make sense sometimes, you can use PDF packages to print a chart or use a package like this: https://github.com/spatie/browsershot

**Comment by chatsikm** [comment]
Awesome, thanks for the info !
