### ISSUE TITLE
Add support for livewire

### ISSUE THREAD

**Issue by roraBIH** [ArielMejiaDev/larapex-charts#21]
Hi,

I am trying to implement larapex charts with livewire. It currently works fine.

![image](https://user-images.githubusercontent.com/1820808/119152866-fd044e80-ba50-11eb-941a-5aa3c13b448e.png)

but when I try to add buttons to change the chart with data for that button the chart is not rendered. 

![image](https://user-images.githubusercontent.com/1820808/119152942-10afb500-ba51-11eb-8e01-a2e5006f140c.png)

It seems like it cannot be re-rendered.

Is there a solution to this issue?

**Comment by ArielMejiaDev** [comment]
I am more seasoned on Inertia stack, the package has support for Inertia, for livewire I did not plan to add support at this moment but it could be part of the annual new release.

Right now you can use another excellent package of Andres Santibañez <a target="_blank" href="https://github.com/asantibanez/livewire-charts">here</a>

**Comment by ArielMejiaDev** [comment]
Of course if you want @roraBIH you are welcome to make a PR to the package to add support for livewire :)

**Comment by roraBIH** [comment]
@ArielMejiaDev Thanks for your quick response. I went along with the package from Andres Santibañez and managed to get it working. I will still keep my fingers crossed regarding the support of livewire as I find your package very useful. I can try to create a PR for the support but I am not quite sure how it is supposed to be done.

**Comment by t-prod** [comment]
Hi,

I'm interested to have a compability in Livewire. Anyone knows how we can "refresh" the Chart class ?
It would avoid the empty thing when we do an interaction with LiveWire.

Regards
