### ISSUE TITLE
Combined Charts Possible?

### ISSUE THREAD

**Issue by mikebronner** [ArielMejiaDev/larapex-charts#24]
I would like to create area charts that also have a line chart (to indicate trends), similar to here: https://apexcharts.com/javascript-chart-demos/mixed-charts/line-area/

Is that possible with this package?

**Comment by ArielMejiaDev** [comment]
This type of charts are easily to be done with the package here an example in the official documentation site: https://larapex-charts.netlify.app/more-charts#area

**Comment by mikebronner** [comment]
@ArielMejiaDev I read through the documentation and didn't see how this was possible, as the chart type is defined outside the series data. 

I was asking about mixing a line chart with an area chart, or a bar chart with a line chart, things like that.
