### ISSUE TITLE
polar Area Chart issue

### ISSUE THREAD

**Issue by mohamedhabibwork** [ArielMejiaDev/larapex-charts#25]
![image](https://user-images.githubusercontent.com/64292519/121812646-ee344480-cc68-11eb-820c-9f1d32f74385.png)

## polarAreaChart

not working successflully 

I used example and not woking also;

**Comment by ArielMejiaDev** [comment]
Please share the code, I got some issues that are really not, 

- please check that everything is copied correctly from the official documentation site https://larapex-charts.netlify.app/
- then if it does not work you can see a live example here: https://github.com/ArielMejiaDev/Larapex-Charts-Example the repo is public, so you can see the code and the site is live here: https://larapex-chart-example.herokuapp.com/

if nothing of this works please comment here and we can see the issue together.
