### ISSUE TITLE
How to change font-family for chart ? 

### ISSUE THREAD

**Issue by zizizak** [ArielMejiaDev/larapex-charts#26]
How to change font-family for chart ?

**Comment by ArielMejiaDev** [comment]
Hi @zizizak there is a new method `setFontFamily('Roboto')`, of course you need to add the tag on your html layout to use it.

**Comment by zizizak** [comment]
> Hi @zizizak there is a new method `setFontFamily('Roboto')`, of course you need to add the tag on your html layout to use it.

THANKS
