### ISSUE TITLE
Changing Label Colours

### ISSUE THREAD

**Issue by 0x13ens** [ArielMejiaDev/larapex-charts#28]
Hello! Brilliant plugin but i have a very dark background and when using the charts, I can't seem to change the labels to white. I've published the config file with no label color change option, added text-white to the main div without success, inspected and tried setting it in my custom css with no success... How do we change the label colors? 

```
    'colors' => [
        '#008FFB', '#00E396', '#feb019', '#ff455f', '#775dd0', '#80effe',
        '#0077B5', '#ff6384', '#c9cbcf', '#0057ff', '00a9f4', '#2ccdc9', '#5e72e4'
    ]

`.apexcharts-title-text {
    color: white !important;
}`

does nothing...

**Comment by rudysetiawan** [comment]
yep brilliang plugins and it's so simple :) thank you!
quick question how do you change the color of the hover/modal box?
![image](https://user-images.githubusercontent.com/4197682/155542738-95d2563a-1144-4bbc-a786-72c443f1f79d.png)
