### ISSUE TITLE
How to add some extra options

### ISSUE THREAD

**Issue by Packiyaraj-01** [ArielMejiaDev/larapex-charts#3]
Hi i need some help on how to use this charts
How could i add options for the chart.I like to implement a bar(Column with Data Labels) chart with date basis.

Thanks in advance

**Comment by ArielMejiaDev** [comment]
Hi here some post about how to use the library: 
Dev.to:
https://dev.to/arielmejiadev/create-charts-in-laravel-with-eloquent-and-larapex-charts-5904
Documentation example with a bar chart as you need:
https://arielmejiadev.github.io/LarapexCharts-Documentation/advanceExample.html#bar
