### ISSUE TITLE
How to hide Y axis? plus other options with JS Apex Charts

### ISSUE THREAD

**Issue by spooksie** [ArielMejiaDev/larapex-charts#32]
Loving the package you have created, I'm just stuck finding a way to customise the charts based on what you have done so far. 

How do you hide the Y axis?

Also other options from Apex, how do I add them to my chart?

i.e
https://apexcharts.com/javascript-chart-demos/area-charts/spline/

**Comment by ArielMejiaDev** [comment]
Hi, sorry to answer late what do you mean by "hide Y-axis"?  here you can find a lot of options to customize the charts: https://larapex-charts.netlify.app/4-customizing-charts

To find examples as you add you can search on the official docs on the "more charts" section: https://larapex-charts.netlify.app/3-more-charts

Currently, I am not planning to add more charts at least this year, but if you find a js option that you feel the package needs, you can make a Pull Request.

Thanks for your words 👍
