### ISSUE TITLE
Feature Request: Allow for clicking through data elements or labels to other pages

### ISSUE THREAD

**Issue by amharris** [ArielMejiaDev/larapex-charts#36]
Allowing to click through data elements (such as a slice of a pie chart) or their associated labels to redirect to pages would be a great addition.

Similar solutions have been [suggested](https://github.com/apexcharts/apexcharts.js/issues/1109#issuecomment-561698044) for pure ApexCharts.

**Comment by ArielMejiaDev** [comment]
Cool, if this is something that the pure JS ApexCharts library can do, definitely can be added to the package, at this moment I do have not enough time to add it, but I can schedule it for Christmas Vacations or I can accept a Pull Request if you want.

Thanks for the suggestion.

**Comment by amharris** [comment]
@ArielMejiaDev No problem.  I'd be keen to help contribute but am not too sure on how to best go about it/what the best practices are here, so am a little hesitant to implement something a bit sloppy.  If you'd be happy to suggest how you would go about it, I'd be very keen to have a go.  Otherwise, I'm happy to wait for you to add it around Christmas time.

Thanks.
