### ISSUE TITLE
Dashboard with charts

### ISSUE THREAD

**Issue by tdrabikdev** [ArielMejiaDev/larapex-charts#37]
Hello guys, i am looking for best way to place a couple chars in dashboard, Any suggestions ?

**Comment by ArielMejiaDev** [comment]
Hi @tdrabikdev the package works great with any css, I can suggest you tailwindcss there are a lot of online examples of dashboards and just add the chart method for blade charts there.

Here a few examples:

- https://github.com/wobsoriano/v-dashboard
- https://github.com/tailwindcomponents/dashboard
- https://github.com/estevanmaito/windmill-dashboard-react
