### ISSUE TITLE
Problem with cache

### ISSUE THREAD

**Issue by tdrabikdev** [ArielMejiaDev/larapex-charts#38]
Hello guys, yeah that me again :) i want to use a cached data in redis however i am getting weird results :D 

No cache data;
![image](https://user-images.githubusercontent.com/82902162/130319971-7a0c5c57-ce04-48a5-9f90-98c20f5045c1.png)

Cached data:
![image](https://user-images.githubusercontent.com/82902162/130319986-613976b5-0730-4b35-942f-01455f9c98b9.png)

**Comment by ArielMejiaDev** [comment]
Umm there would not be anything that could be different, but please provide more context to help you

**Comment by ArielMejiaDev** [comment]
I was not able to get more context, so I will close the issue...
