### ISSUE TITLE
How to set the chart height?

### ISSUE THREAD

**Issue by DevTiago** [ArielMejiaDev/larapex-charts#39]
Greetings,

Thanks a lot for this package! 

I'm trying it on a Laravel Project but i can set the height of the chart... i can change the width but the height keeps the same.

Any advice?

**Comment by ArielMejiaDev** [comment]
Hi @DevTiago the hight can be set with a setter, try adding:

```php
$chart->setHeight(700)
```

take in mind that the number would be the pixels, you can also customize more the charts here the docs to get more examples: https://larapex-charts.netlify.app/4-customizing-charts
