### ISSUE TITLE
Publishing stubs and commands

### ISSUE THREAD

**Issue by kamilkozak** [ArielMejiaDev/larapex-charts#40]
The stubs and commands are published by the service provider each time the application is started, so manual removal does not help. This is the first time I encounter such strange behavior. Besides, I like the package very much.

**Comment by Krato** [comment]
Yes. Should be only published on `vendor:publish`. No every time.

**Comment by ArielMejiaDev** [comment]
Hi @kamilkozak and @Krato I am deeply sorry about the behavior it could lead to multiple problems using Laravel Octane for example so I will make a release as soon as possible to change this behavior and publish only by `vendor:publish` the command and the stubs would probably would be available only in the vendor directory but the stubs could be published maybe to customize the chart class boilerplate

**Comment by Krato** [comment]
Any update?

**Comment by Andrew-Hike** [comment]
this will break on anything hosted on serverless as well.
I fixed it by simply commenting out the lines that publish the stubs and commands from the boot method of the service provider

**Comment by ArielMejiaDev** [comment]
@kamilkozak @Krato @Andrew-Hike there is a new release that solves this issue.
