### ISSUE TITLE
Poor handling of decimals

### ISSUE THREAD

**Issue by Eixix** [ArielMejiaDev/larapex-charts#41]
Hey it's me again,

When using the following: 
```php
$chart = LarapexChart::areaChart()
            ->setTitle('Einnahmen pro Semester')
            ->addData('Sales', [658.6, 519.38])
            ->setXAxis(["WiSe 2020\/2021","SoSe 2021"]);
```

the dataset inside the chart object will look like this:
```json
dataset: "[{"name":"Sales","data":[658.5999999999999,519.3799999999999]}]"
```

This implies, that decimals are handled as floats somewhere, it leads to poor displaying of correct numbers inside the chart.

Thanks for reading, I really like your library :)

**Comment by ArielMejiaDev** [comment]
Hi @Eixix this behavior is something that I cannot handle efficiently... I try a lot of things but at the package just make a `pending object` that would be render in a javascript script, I could not find a way to change this format in javascript, but if you have an idea about how I could add this you are totally welcome to make a PR
