### ISSUE TITLE
copy(app/Console/Commands/ChartMakeCommand.php): Failed to open stream: Permission denied

### ISSUE THREAD

**Issue by magarrent** [ArielMejiaDev/larapex-charts#44]
Hi @ArielMejiaDev ! I'm having problems updating from php 7.4 to 8.0. I'm using Vagrant + Homestead and your package throws me this error:

`copy(/home/vagrant/code/<project>/app/Console/Commands/ChartMakeCommand.php): Failed to open stream: Permission denied
`

![image](https://user-images.githubusercontent.com/6561770/141099368-dd881a83-4b07-4842-8e24-d2269ad3a27e.png)

Any ideas? The command file already exists

**Comment by alexv96** [comment]
How did you solve it?

**Comment by magarrent** [comment]
> How did you solve it?

I had problems with Homestead v9 and PHP 8 projects, some issues with permissions. I use valet now and it works...
