### ISSUE TITLE
Tooltip / hover not working well

### ISSUE THREAD

**Issue by JessedeB** [ArielMejiaDev/larapex-charts#45]
https://gyazo.com/0036b5a5d371f8bed4a42d3055f1f892

The hover to show the data only shows when you hover on the labels it self.
Tried to pull in the latest cdn and host the js files myself but that didn't work.

Cheers :)

**Comment by JessedeB** [comment]
The problem seems to come fromt the script.blade.php at  grid: {!! $chart->grid() !!}, when turned of the grid is working like a charm.

**Comment by ArielMejiaDev** [comment]
I double check this issue, the syntax of the package could be confusing, so to avoid issues by default the charts are going to work without grid, if you choose to generate a chart using the `make:chart` command you would get different styles based on your selected chart type, but you can override this easily:

To set a default grid (gray with opacity... plays really well with tailwindUI gray colors)

```php
$chart
    ->areaChart()
    ->setGrid()
```

To customize the grid you can pass color as a string in hex value and a number for the opacity:

```php
$chart
    ->areaChart()
    ->setGrid('#93c5fd', 0.2)
```

To remove the grid, just remove the `setGrid` method:

```php
$chart
    ->areaChart()
```
