### ISSUE TITLE
Pareto Graph its possible?

### ISSUE THREAD

**Issue by mafalda2007** [ArielMejiaDev/larapex-charts#49]
Is it possible to create this graph?
![image](https://user-images.githubusercontent.com/18195074/152794099-c91e32ab-65e3-431c-a872-0eeb436bbc7c.png)

**Comment by ArielMejiaDev** [comment]
Hi @mafalda2007 this is something that is posible to be done using apexcharts js as this is the based library to render the charts:

https://apexcharts.com/javascript-chart-demos/mixed-charts/line-column-area/

As there is an object in the example, it is posible to make this work with larapex charts, this is a feature that I can make during in my free time, but it would take a while... feel free to make a PR
