### ISSUE TITLE
Is there a way to embed the chart in a PDF?

### ISSUE THREAD

**Issue by jeangomes** [ArielMejiaDev/larapex-charts#53]
I use MPDF to generate PDF's. Is possible?

**Comment by ArielMejiaDev** [comment]
You should search about printing a "canva" using the library, I played with that a little bit a few years ago, maybe you should consider using some other library that directly print the HTML.

The easier approach:

- Make a JS button to print the page
- Add styles to your page specifically to print (css has its own)
- Add `setSparklines()` method to your chart to keep it as clean as possible

another good option is this package from spatie: https://spatie.be/docs/browsershot/v2/usage/creating-pdfs

Just take in mind that your server would require some php extensions
