### ISSUE TITLE
Can you hide all data with one button?

### ISSUE THREAD

**Issue by jamesmills** [ArielMejiaDev/larapex-charts#55]
Hi,

Firstly let me start with a huge thanks for this great package!

I know that clicking on a legend item will show/hide it from the graph

> Interactivity with Legend
> Enable show/hide a series when it is clicked
> When a user clicks a legend, the series associated with that legend is toggled in appearance.
>   legend: {
>     onItemClick: {
>       toggleDataSeries: true
>     },
>   }

I was wondering if anyone has a working example using this package where you can add a button to show/hide all series data or select which is shown on loading the graph?

Thanks in advance!

James

**Comment by ArielMejiaDev** [comment]
@jamesmills if you can provide a full frontend (only js) example of how it should works, I can definitely think about some way to make this happen.

**Comment by ArielMejiaDev** [comment]
@jamesmills something like this? 

That hide a series when the right corner dots are clicked?

https://apexcharts.com/javascript-chart-demos/line-charts/data-labels/

**Comment by jamesmills** [comment]
Hi @ArielMejiaDev 

Thanks for getting back to me.

I have a line graph with loads of lines... and they all have labels... I can click on individual labels and that will hide that individual line. What I was hoping for was an option to "show all" or "hide all" and then you could click on a couple of labels to have them shown on the graph. Otherwise, it's a long process of clicking on loads of labels to hide them from the graph.

I've not managed to find this in the Apex Chart docs yet :-(

Thanks, James
