### ISSUE TITLE
Adding support for Sparklines chart type

### ISSUE THREAD

**Issue by jamesmills** [ArielMejiaDev/larapex-charts#57]
Following on from [this thread on Twitter ](https://twitter.com/jamesmills/status/1546108256149536768).

These are the bad boys I'm looking for!

https://apexcharts.com/javascript-chart-demos/sparklines/basic/
https://apexcharts.com/javascript-chart-demos/dashboards/modern/

At first look I think we can just create a new chart type class but I'm not sure, I'm going to take a look this week.

**Comment by jamesmills** [comment]
So it looks like in the `scrip.blade.php` file if you add the sparkline enabled flag this automatically works.

```
chart: {
            type: '{!! $chart->type() !!}',
            ...
            foreColor: '{!! $chart->foreColor() !!}',
            sparkline: {
                enabled: true
            },
        },
```

So now I'll investigate if we can add something like a `setSparkline()` or similar on the `ArielMejiaDev\LarapexCharts\LarapexChart` class.

Then update the `script.blade.php` file to include this if enabled. 

Just need to investigate what needs to be done for the other implementations like Vue etc. Looks like we need to update the `toJson()` function to check if Sparkline is enabled.

**Comment by jamesmills** [comment]
@ArielMejiaDev if I look at PR'ing this would it make it into prod or would we have to wait for a new version?

**Comment by ArielMejiaDev** [comment]
Sorry for the delay @jamesmills I had been busy, your contributions are awesome, your PR was added in the 4.x release, I add a new release `5.0.0` it resolves some issues related to publish unnecessary files.
