### ISSUE TITLE
is there a way to use percentage value?

### ISSUE THREAD

**Issue by Yandiio** [ArielMejiaDev/larapex-charts#62]

**Comment by ArielMejiaDev** [comment]
There is definitely a way to add this using the apexcharts js library directly.

Here you can see an example of how to add a percentage or any other suffix to a pop over
https://apexcharts.com/javascript-chart-demos/bar-charts/stacked/

An another example of how to add the same customized suffix to the series of values
https://stackoverflow.com/questions/67228705/apexcharts-js-line-chart-display-percent-from-total-in-tooltip

This is an addition that I have plan for the next release, but I have no date for that feature.

Feel free to add a PR to add this feature.
