### ISSUE TITLE
setSparkline returns undefined method

### ISSUE THREAD

**Issue by rgbaman** [ArielMejiaDev/larapex-charts#65]
Great work on the library.

I've just upgraded to v5 for the `setSparkline` support. Unfortunately I get the following error:

`Call to undefined method ArielMejiaDev\LarapexCharts\LineChart::setSparkline()`

Chart code:

```
public function build(): LineChart
    {
        return $this->chart->lineChart()
            ->addData('Physical sales', [40, 93, 35, 42, 18, 82])
            ->setSparkline();
    }
```
I've tried to debug as much as I can but can't get to the bottom of it. I'm running version 5.1.0.

**Comment by ArielMejiaDev** [comment]
Please update to 5.2 version or higher it should work properly now, thanks.
