### ISSUE TITLE
Formatting of yaxis and labels

### ISSUE THREAD

**Issue by AaronNeonDigital** [ArielMejiaDev/larapex-charts#66]
As seen on ApexCharts, there is a possibility of formatting y-axis and labels, also seen an issue posted before, which was closed.

Is this a feature not documented? I have tried looking through the code, don't see anything obvious.

**Comment by zwhhz** [comment]
I need it too, so I've made a merge request: #78

**Comment by ArielMejiaDev** [comment]
Thanks, @zwhhz I am going to check the PR as soon as possible
