### ISSUE TITLE
Upgrade development requirement to support laravel 10.x

### ISSUE THREAD

**Issue by Mig0o0** [ArielMejiaDev/larapex-charts#71]
Hi Ariel, While Installing Your Awsome project on a new laravel project with the newest version it tells me 

> that illuminate/support is not fit the requirement of your project

, since  the new version of `illuminate/support is 10.0` but your project required **8.0/9.0**, and this makes a conflict with the most recent laravel version

**Comment by enrymari** [comment]
I've the same problem: i can't use your project, please update it!

**Comment by ArielMejiaDev** [comment]
It has been updated, sorry for the delay.
