### ISSUE TITLE
Unable to use make:chart artisan CLI

### ISSUE THREAD

**Issue by OOOOAAAAEEEEEE** [ArielMejiaDev/larapex-charts#77]
For another context:
I'm using Laravel 10.0,
already reinstall the dependencies,
the dependencies using v2.1

The error showing like this.

![image](https://github.com/ArielMejiaDev/larapex-charts/assets/69966462/d5a8a48b-faa3-40ec-9d34-d1961b2b26a6)

EDIT: 

After i read another issues i already read the same problem as me, the answer is, i must update my dependencies into 3.0 or greater, but the problem is, i can't update it because the requirement is need to be laravel 9.0 etc.

![image](https://github.com/ArielMejiaDev/larapex-charts/assets/69966462/04be58c5-d52a-4c1a-85e1-ead7937c5260)

**Comment by ArielMejiaDev** [comment]
in this case You can still use the library just take in mind that you should create your own classes where you require it and instantiate the chart classes by yourself, the command only creates the files for you and give you a nice boilerplate based on the docs site to give you a little chart class that you are able to customize as you need.
