### ISSUE TITLE
Wrong publish command for chart stubs in the docs

### ISSUE THREAD

**Issue by jivanf** [ArielMejiaDev/larapex-charts#79]
In the [Customize chart stubs](https://larapex-charts.netlify.app/8-customize-chart-stubs/) section of the docs, the following command is shown to publish the stubs:

`php artisan vendor:publish --tag=larapex-charts-apexcharts-stubs`

However, the tag used in the command doesn't exist. Instead, the `larapex-charts-stubs` tag needs to be used like this:

`php artisan vendor:publish --tag=larapex-charts-stubs`

I was looking to open a PR to fix this, but it seems the docs aren't in this repo, so I opened this issue instead.

**Comment by JohnMSykes** [comment]
Hi jivanf - Thanks for posting this - I was caught out by this issue, too. I can confirm that this command works with Larapex 6.0.0:

```
johnmsykes@Sykes-P16s:~/src/zmr$ sail artisan vendor:publish --tag=larapex-charts-stubs

   INFO  Publishing [larapex-charts-stubs] assets.

  Copying directory [vendor/arielmejiadev/larapex-charts/stubs/stubs] to [stubs] .......................................................... DONE

johnmsykes@Sykes-P16s:~/src/zmr$
```

**Comment by ArielMejiaDev** [comment]
Thanks @jivanf I am going to update the docs site as soon as possible, nice catch
