### ISSUE TITLE
Latest version requires php 8

### ISSUE THREAD

**Issue by snapey** [ArielMejiaDev/larapex-charts#80]
The package contains code that requires php8 but composer.json still accepts php 7.4

https://github.com/ArielMejiaDev/larapex-charts/blob/21dc8bfd8f9577ac51e5031de643aa7130679771/src/LarapexChart.php#L28

gives `ParseError syntax error, unexpected '|', expecting variable`

**Comment by thinkverse** [comment]
Related discussion on Laracasts: https://laracasts.com/discuss/channels/laravel/syntax-error-unexpected-expecting-variable-t-variable-1

**Comment by ArielMejiaDev** [comment]
Thanks for reporting the issue, I am going to add a patch release soon
