### ISSUE TITLE
How to export chart to png/jpg?

### ISSUE THREAD

**Issue by kahfieidn** [ArielMejiaDev/larapex-charts#88]
hello, how to export chart to png/jpg using larapex?

**Comment by ArielMejiaDev** [comment]
To export it as PDF you should a library that uses something like headless chrome behind the scenes, a great package to make something like this would be: 

https://spatie.be/docs/laravel-pdf/v1/introduction

To export it to Excel at this point I did not figure out a way to make it, but I would be totally open to a PR if you are able to figure it out.
