### ISSUE TITLE
Global colors not setting

### ISSUE THREAD

**Issue by roachadam** [ArielMejiaDev/larapex-charts#9]
Could possibly be user error, but the global colors do not set properly and thus chart does not print.

I have created the larapex-charts config file with colors.

![image](https://i.imgur.com/lIWLGP5.png)

js
![image](https://i.imgur.com/yOpUnpk.png)

notice: colors:null
Temporary fix is to add the colors manually to each chart.

Laravel v8.x

**Comment by ArielMejiaDev** [comment]
I will check on Laravel 7 & 8, thanks for reporting the issue.

**Comment by ArielMejiaDev** [comment]
You need to publish the package config file to get the custom colors array by using this command:

```php
php artisan vendor:publish --tag=larapex-charts-config
```
