### ISSUE TITLE
How to turn the legend off?

### ISSUE THREAD

**Issue by lukejames1111** [ArielMejiaDev/larapex-charts#94]
I'm looking for a way to turn the legend off directly in Laravel without using CSS. I have tried this to no avail:

```
return $this->chart->donutChart()
    ->setTitle('Valuations Outcome')
    ->addData($data)
    ->setLabels($labels)
    ->setOptions([
        'legend' => [
            'show' => false
        ]
]);
```

**Comment by ArielMejiaDev** [comment]
Hey @lukejames1111 this ability has been added with a setter by @zwhhz

**Comment by lukejames1111** [comment]
Thanks for this, but I've got no idea how to actually turn it off. What is the setter I should be using to remove it?
